version: "3"

services:
  ###_lightningd:
    restart: unless-stopped
    stop_signal: SIGKILL
    image: btcpayserver/lightning:v0.6.3-3-dev
    environment: 
      EXPOSE_TCP: "true"
      LIGHTNINGD_OPT: |
        bitcoin-datadir=/etc/bitcoin
        bitcoin-rpcconnect=bitcoind:${TESTER_BITCOIN_RPCPORT:?NoMainBitcoinRPCPort}
        bitcoin-rpcuser=ceiwHEbqWI83
        bitcoin-rpcpassword=DwubwWsoo3
        network=${TESTER_NETWORK:-regtest}
        bind-addr=0.0.0.0
        announce-addr=###_lightningd
        log-level=debug
        dev-broadcast-interval=1000
        dev-bitcoind-poll=1
    ports:
      - "${###_PORT:?NoClightningPort}:9835" # api port
    expose:
      - "9735" # server port
      - "9835" # api port
    volumes:
      - "lightningd_###_dir:/root/.lightning" # sadly relative path is not working for clightning
      - "${TESTER_DATADIR:?NoTesterDataDir}/bitcoind_dir:/etc/bitcoin"
    links:
      - bitcoind
volumes:
    lightningd_###_dir:
